### ISSUE TITLE
Problem with CUDA Memory needed

### ISSUE THREAD

**Issue by AMBBe** [diptamath/Nonhomogeneous_Image_Dehazing#4]
I try again and again on google colab for running this code with 15 GB GPU Memory but I can't successfully
I try it with reduce batch size and use below code but not work

import gc
gc.collect()
torch.cuda.empty_cache()

and I get this error after run  it:

init data folders
load encoder_lv1 success
load encoder_lv2 success
load encoder_lv3 success
load encoder_lv1 success
load decoder_lv2 success
load decoder_lv3 success
/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py:154: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
Training...
Traceback (most recent call last):
  File "DMPHN_train.py", line 262, in <module>
    main()
  File "DMPHN_train.py", line 157, in main
    feature_lv3_3 = encoder_lv3(images_lv3_3)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/My Drive/Nonhomogeneous_Image_Dehazing-master/models.py", line 48, in forward
    x = self.layer2(x) + x
RuntimeError: CUDA out of memory. Tried to allocate 470.00 MiB (GPU 0; 14.76 GiB total capacity; 13.60 GiB already allocated; 23.75 MiB free; 13.68 GiB reserved in total by PyTorch)

Please help me

**Comment by AMBBe** [comment]
I have this error after run DMPHN_train.py

**Comment by saikatdutta** [comment]
What is the lowest batch size that you've tried with?

**Comment by AMBBe** [comment]
4 and 2 for batch size

**Comment by AMBBe** [comment]
Do you run DMPHN_train.py on colab without this error?
I try it with 2,4,8,16 batch size but it's nit work
Plz help me

**Comment by AMBBe** [comment]
I use NH-HAZE dataset for train. Do you use it or another dataset?

**Comment by saikatdutta** [comment]
Training is done on NH-Haze 2020. Please close this issue if resolved.

**Comment by shimaamohammed121** [comment]
I have the same error when i run DMPHN_train.py on colab .can  you help me solve this error?

**Comment by AMBBe** [comment]
You can run the code without custom_loss function and use mse for it, this
code is comment in the main file and use batch size less than 32. You
should run code without test section.

**Comment by shimaamohammed121** [comment]
I do this modification and I have the same error and I also  run the code on google colab bro   @AMBBe

**Comment by Aomrlyliliya** [comment]
Do you solve this problem?I have the same problem as you.

**Comment by AMBBe** [comment]
Hi
Yes, I can solve this problem by using google colab for run the code

**Comment by Aomrlyliliya** [comment]
Thank you for your review. I run the code in google colab but I got the same error of cuda out of memory. I also run the code without custom_loss function and use mse for it,  and use batch size less than 32. And I run code without test section as you said.But it doesn't work.Can you tell me your settings?
